name: Generate M3U

on:
  schedule:
    - cron: "0 2 * * *"   # 每天早上 2 点运行一次（UTC 时间，北京时间+8）
  workflow_dispatch:       # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      run: python generate_m3u.py

    - name: Commit result
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add valid.m3u
        git commit -m "Update valid.m3u" || echo "No changes"
        git push
